# Generated by Django 3.1.7 on 2021-02-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210220_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='abstract',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='category',
            field=models.CharField(choices=[('T', 'Prednášky'), ('W', 'Workshop'), ('M', 'Jedlo'), ('O', 'Ostatné')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.DateTimeField(unique=True),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_events', to='core.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='participation',
            field=models.ManyToManyField(through='core.Participation', to='core.Event'),
        ),
    ]
