# Generated by Django 3.1.7 on 2021-02-21 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210221_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='participation',
            new_name='participations',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='institute',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Astroworkshop', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.DateTimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.institute')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='affiliations',
            field=models.ManyToManyField(through='core.Affiliation', to='core.Institute'),
        ),
    ]
