# Generated by Django 3.1.7 on 2021-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210221_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
