# Generated by Django 3.1.7 on 2021-02-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210221_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='online',
        ),
        migrations.AddField(
            model_name='participation',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
