# Generated by Django 3.1.7 on 2021-02-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210221_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['start', 'speaker']},
        ),
    ]
