# Generated by Django 3.1.7 on 2021-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210221_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.CharField(choices=[('T', 'Prednáška'), ('W', 'Workshop'), ('M', 'Jedlo'), ('O', 'Ostatné')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
