# Generated by Django 3.1.7 on 2021-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210222_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.CharField(default='2021', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
