# Generated by Django 3.1.7 on 2021-02-22 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('abstract', models.TextField(blank=True, max_length=4096, null=True)),
                ('start', models.DateTimeField(blank=True, null=True, unique=True)),
                ('duration', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('T', 'Prednáška'), ('W', 'Workshop'), ('M', 'Jedlo'), ('O', 'Ostatné')], default='T', max_length=1)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start', 'person'],
            },
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
    ]
