# Generated by Django 3.1.7 on 2021-02-24 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210223_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start']},
        ),
        migrations.RemoveField(
            model_name='slot',
            name='person',
        ),
        migrations.AddField(
            model_name='slot',
            name='person',
            field=models.ManyToManyField(related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
