# Generated by Django 3.1.7 on 2021-02-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210224_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start', 'name')},
        ),
        migrations.AddField(
            model_name='participant',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='organizer',
            field=models.BooleanField(default=False),
        ),
    ]
