# Generated by Django 3.1.7 on 2021-02-28 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210227_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participations',
            field=models.ManyToManyField(related_name='participants', through='core.Participation', to='core.Event'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
