# Generated by Django 3.1.7 on 2021-03-05 22:12

import core.models.participant
import core.models.slot
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210228_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['event']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start', 'duration']},
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
                ('objects', core.models.participant.ParticipantManager()),
            ],
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='participations',
            new_name='events',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='affiliations',
        ),
        migrations.AddField(
            model_name='participant',
            name='institutes',
            field=models.ManyToManyField(related_name='people', through='core.Affiliation', to='core.Institute'),
        ),
        migrations.AddField(
            model_name='slot',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to=core.models.slot.presentation_filename),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='core.institute'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
