# Generated by Django 3.1.7 on 2021-03-10 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210310_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
