# Generated by Django 3.1.7 on 2021-03-13 22:44

import core.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210310_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf_programme',
            field=models.FileField(blank=True, null=True, upload_to=core.models.event.event_filename),
        ),
        migrations.AddField(
            model_name='slot',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
