# Generated by Django 4.1.1 on 2022-09-10 21:54

import core.models.event
import core.models.slot
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210313_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['start'], 'verbose_name': 'afiliácia', 'verbose_name_plural': 'afiliácie'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start', 'name'), 'verbose_name': 'workshop', 'verbose_name_plural': 'workshopy'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['full_name'], 'verbose_name': 'inštitúcia', 'verbose_name_plural': 'inštitúcie'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'účastník', 'verbose_name_plural': 'účastníci'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['event', 'person']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start', 'duration'], 'verbose_name': 'slot', 'verbose_name_plural': 'sloty'},
        ),
        migrations.AlterModelManagers(
            name='participant',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='video',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL videa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='kód'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='koniec'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='názov'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pdf_programme',
            field=models.FileField(blank=True, null=True, upload_to=core.models.event.event_filename, verbose_name='program (PDF)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='začiatok'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='abstract',
            field=models.TextField(blank=True, max_length=4096, verbose_name='abstrakt'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='category',
            field=models.CharField(choices=[('T', 'Prednáška'), ('W', 'Workshop'), ('M', 'Jedlo'), ('O', 'Ostatné')], default='T', max_length=1, verbose_name='kategória'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='dĺžka (min)'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.event', verbose_name='workshop'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='note',
            field=models.CharField(blank=True, max_length=256, verbose_name='poznámka'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='online',
            field=models.BooleanField(default=False, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='slots', to=settings.AUTH_USER_MODEL, verbose_name='účastník'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to=core.models.slot.presentation_filename, verbose_name='prezentácia (PDF)'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='začiatok'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='title',
            field=models.CharField(blank=True, max_length=256, verbose_name='názov'),
        ),
    ]
