# Generated by Django 4.1.1 on 2022-09-10 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_affiliation_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='koniec'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to='core.institute', verbose_name='inštitúcia'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation', to=settings.AUTH_USER_MODEL, verbose_name='osoba'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='začiatok'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='full_name',
            field=models.CharField(max_length=256, verbose_name='plné meno'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='short_name',
            field=models.CharField(max_length=32, verbose_name='kód'),
        ),
    ]
