# Generated by Django 4.1.7 on 2023-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_affiliation_end_alter_affiliation_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
